
branches:
  only:
    - master

language: cpp
compiler: 
  - g++
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - clang

install: 
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script: 
- ulimit -c unlimited -S # enable core files
- mkdir -p build # create build directory if it does not exists
- (cd build; cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX .. && make) # make
- (cd tests && ctest -V) # run tests

after_failure: ./scripts/after-failure.sh

