
branches:
  only:
    - master

language: cpp

os:
  - linux

env:
  - COVERAGE=ON
  - COVERAGE=OFF

compiler: 
  - g++
  - clang

matrix:
  exclude:
    - compiler: clang
      env: COVERAGE=ON

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - g++-4.9
    - clang
    - cmake-data
    - cmake

install: 
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script: ./scripts/build.sh 
